// Presets de qualidade. "Média" é o alvo de 60 fps em PC médio.

export const QUALITY = {
  low: {
    label: 'Baixa',
    pixelRatio: 0.75,
    shadowSize: 1024,
    shadowRange: 32,
    grassNear: 26000,
    grassNearR: 18,
    grassFar: 26000,
    grassFarR: 42,
    post: false,
    bloom: false,
    ao: false,
    msaa: 0,
    antialias: false,
  },
  medium: {
    label: 'Média',
    pixelRatio: 1,
    shadowSize: 2048,
    shadowRange: 42,
    grassNear: 70000,
    grassNearR: 24,
    grassFar: 75000,
    grassFarR: 62,
    post: true,
    bloom: true,
    ao: false,
    msaa: 4,
    antialias: false,
  },
  high: {
    label: 'Alta',
    pixelRatio: 1.5,
    shadowSize: 4096,
    shadowRange: 52,
    grassNear: 130000,
    grassNearR: 30,
    grassFar: 110000,
    grassFarR: 85,
    post: true,
    bloom: true,
    ao: true,
    msaa: 4,
    antialias: false,
  },
};
