// Dados das duas cidades: estações, marcos, falas.
// Latitude/longitude em graus sobre o planetinha (norte = +lat, leste = +lon).

export const CITIES = {
  jaipur: {
    id: 'jaipur',
    lang: 'hi',
    script: 'जयपुर',
    latin: 'Jaipur',
    nick: 'A Cidade Rosa',
    accent: '#c8506a',
    about: 'Pintada de rosa em 1876 para receber visitas. Palácios de arenito, bazares de joias, camelos na avenida e o céu cheio de pipas. O <b>Palace on Wheels</b> dá a volta no equador.',
    trainName: 'Palace on Wheels',
    trainKind: 'train',
    ground: 0xd9b98a,
    road: 0x9c8a78,
    stations: [
      { lon: 0, deva: 'जयपुर जंक्शन', latin: 'Jaipur Junction' },
      { lon: 72, deva: 'गांधीनगर', latin: 'Gandhinagar' },
      { lon: 144, deva: 'दुर्गापुरा', latin: 'Durgapura' },
      { lon: 216, deva: 'सांगानेर', latin: 'Sanganer' },
      { lon: 288, deva: 'ढेहर का बालाजी', latin: 'Dhehar ka Balaji' },
    ],
    landmarks: [
      { key: 'hawaMahal', lat: 13, lon: 24, zone: 13, deva: 'हवा महल', latin: 'Hawa Mahal', desc: 'O Palácio dos Ventos: 953 janelinhas para ver a rua sem ser vista.' },
      { key: 'jantarMantar', lat: -15, lon: 100, zone: 12, deva: 'जंतर मंतर', latin: 'Jantar Mantar', desc: 'O relógio de sol mais alto do mundo, de 1734.' },
      { key: 'albertHall', lat: 17, lon: 168, zone: 11, deva: 'अल्बर्ट हॉल', latin: 'Albert Hall', desc: 'Museu indo-sarraceno no meio do jardim Ram Niwas.' },
      { key: 'jalMahal', lat: -36, lon: 222, zone: 16, deva: 'जल महल', latin: 'Jal Mahal', desc: 'O palácio que flutua no lago Man Sagar.' },
      { key: 'patrikaGate', lat: -13, lon: 300, zone: 9, deva: 'पत्रिका गेट', latin: 'Patrika Gate', desc: 'Um portão pintado de todas as cores do Rajastão.' },
      { key: 'johari', lat: 10, lon: 330, zone: 10, deva: 'जौहरी बाज़ार', latin: 'Johari Bazaar', desc: 'O bazar dos joalheiros, sob as arcadas rosadas.' },
      { key: 'amer', lat: 90, lon: 0, zone: 20, deva: 'आमेर का किला', latin: 'Forte de Amer', desc: 'Muralhas de mel no topo do mundo. Entre pelo Suraj Pol.' },
      { key: 'kites', lat: -90, lon: 0, zone: 18, deva: 'पतंगबाज़ी', latin: 'Campo das pipas', desc: 'Todo dia é Makar Sankranti no polo sul.' },
    ],
    roles: [
      { who: 'Vendedor de kachori', lines: [2, 0] },
      { who: 'Condutor de camelo', lines: [6, 1] },
      { who: 'Menina da pipa', lines: [4, 0] },
      { who: 'Guarda da estação', lines: [7, 0] },
      { who: 'Joalheiro', lines: [8, 1] },
      { who: 'Guia de turismo', lines: [3, 5] },
      { who: 'Senhor de turbante', lines: [0, 1, 5] },
      { who: 'Chaiwala', lines: [9, 0] },
    ],
    lines: [
      ['राम राम सा!', 'Rām Rām sā!', 'Olá! (o cumprimento do Rajastão)'],
      ['पधारो म्हारे देस!', 'Padhāro mhāre des!', 'Seja bem-vindo à minha terra!'],
      ['प्याज़ की कचौरी खाओगे? अभी गरम है।', 'Pyāz kī kachaurī khāoge? Abhī garam hai.', 'Quer uma kachori de cebola? Está quentinha.'],
      ['हवा महल में नौ सौ तिरपन झरोखे हैं।', 'Havā Mahal meṁ nau sau tirpan jharokhe haiṁ.', 'O Hawa Mahal tem 953 janelinhas.'],
      ['संक्रांति पर पूरा आसमान पतंगों से भर जाता है।', 'Saṅkrānti par pūrā āsmān pataṅgoṁ se bhar jātā hai.', 'No Sankranti o céu inteiro se enche de pipas.'],
      ['शहर गुलाबी क्यों है? मेहमानों के स्वागत के लिए!', 'Śahar gulābī kyoṁ hai? Mehmānoṁ ke svāgat ke lie!', 'Por que a cidade é rosa? Para receber as visitas!'],
      ['ऊँट की सवारी करोगे?', 'Ūṁṭ kī savārī karoge?', 'Quer dar uma volta de camelo?'],
      ['गाड़ी पाँच मिनट में आएगी।', 'Gāṛī pāṁc minaṭ meṁ āegī.', 'O trem chega em cinco minutos.'],
      ['यह पन्ना असली है, देखो कैसे चमकता है।', 'Yah pannā aslī hai, dekho kaise camaktā hai.', 'Essa esmeralda é de verdade, olha como brilha.'],
      ['एक कटिंग चाय?', 'Ek kaṭiṅg cāy?', 'Meio copo de chá?'],
    ],
  },

  kolkata: {
    id: 'kolkata',
    lang: 'bn',
    script: 'কলকাতা',
    latin: 'Kolkata',
    nick: 'A Cidade da Alegria',
    accent: '#d4a017',
    about: 'Táxis amarelos, casarões com venezianas verdes, chá em copinho de barro e a ponte de Howrah sobre o Hooghly. O último <b>bonde</b> da Índia ainda circula pelo equador.',
    trainName: 'Bonde de Calcutá',
    trainKind: 'tram',
    ground: 0xa9b58a,
    road: 0x6e6a66,
    river: { lon: 90, halfWidth: 5.6, lat0: -26, lat1: 26, bridgeHalf: 2.2 },
    stations: [
      { lon: 0, deva: 'ধর্মতলা', latin: 'Esplanade' },
      { lon: 58, deva: 'হাওড়া', latin: 'Howrah' },
      { lon: 150, deva: 'শ্যামবাজার', latin: 'Shyambazar' },
      { lon: 220, deva: 'গড়িয়াহাট', latin: 'Gariahat' },
      { lon: 290, deva: 'টালিগঞ্জ', latin: 'Tollygunge' },
    ],
    landmarks: [
      { key: 'howrah', lat: 0, lon: 90, zone: 12, deva: 'হাওড়া ব্রিজ', latin: 'Ponte de Howrah', desc: 'Cantiléver de aço sobre o Hooghly, sem um único parafuso.' },
      { key: 'prinsep', lat: -17, lon: 80.5, zone: 7, deva: 'প্রিন্সেপ ঘাট', latin: 'Prinsep Ghat', desc: 'Um pavilhão paladiano na beira do rio.' },
      { key: 'victoria', lat: -22, lon: 160, zone: 17, deva: 'ভিক্টোরিয়া মেমোরিয়াল', latin: 'Victoria Memorial', desc: 'Mármore branco no meio do Maidan.' },
      { key: 'writers', lat: 15, lon: 26, zone: 13, deva: 'রাইটার্স বিল্ডিং', latin: "Writers' Building", desc: 'Tijolo vermelho, colunas brancas, dois séculos de papelada.' },
      { key: 'pandal', lat: 18, lon: 240, zone: 11, deva: 'দুর্গা পুজো', latin: 'Pandal da Durga Puja', desc: 'A deusa de dez braços, sob luzes que nunca se apagam.' },
      { key: 'collegeSt', lat: -15, lon: 300, zone: 10, deva: 'কলেজ স্ট্রিট', latin: 'College Street', desc: 'Um quilômetro de livros de segunda mão.' },
      { key: 'minar', lat: 90, lon: 0, zone: 13, deva: 'শহিদ মিনার', latin: 'Shaheed Minar', desc: 'A coluna de 48 metros no topo do Maidan.' },
      { key: 'dakshineswar', lat: -90, lon: 0, zone: 15, deva: 'দক্ষিণেশ্বর', latin: 'Templo de Dakshineswar', desc: 'Nove torres para a deusa Kali.' },
    ],
    roles: [
      { who: 'Chaiwala', lines: [2, 0] },
      { who: 'Taxista', lines: [7, 1] },
      { who: 'Livreiro', lines: [6, 8] },
      { who: 'Estudante', lines: [8, 4] },
      { who: 'Vendedor de mishti', lines: [3, 0] },
      { who: 'Artesão de Kumartuli', lines: [5, 0] },
      { who: 'Condutor do bonde', lines: [4, 1] },
      { who: 'Senhora do mercado', lines: [1, 3] },
    ],
    lines: [
      ['নমস্কার!', 'Nômoshkar!', 'Olá!'],
      ['কেমন আছেন, দাদা?', 'Kemon achhen, dada?', 'Como vai, irmão?'],
      ['এক ভাঁড় চা হবে?', 'Ek bhãṛ cha hobe?', 'Um copinho de barro com chá?'],
      ['মিষ্টি না খেয়ে যাবেন না!', 'Mishṭi na kheye jaben na!', 'Não vá embora sem provar um doce!'],
      ['ট্রামে চড়ুন, তাড়াহুড়োর কী আছে?', 'Ṭrame chôṛun, taṛahuṛor ki achhe?', 'Vá de bonde — pra que a pressa?'],
      ['পুজোর সময় সারা রাত শহর জেগে থাকে।', 'Pujor shômoy sara rat shôhor jege thake.', 'Na época da Puja a cidade fica acordada a noite toda.'],
      ['কলেজ স্ট্রিটে সব বই পাবেন।', 'College Streeṭe shôb bôi paben.', 'Na College Street você acha qualquer livro.'],
      ['হাওড়া যাবেন? মিটারে চলবে।', 'Haoṛa jaben? Miṭare chôlbe.', 'Vai pra Howrah? Vamos no taxímetro.'],
      ['আড্ডা ছাড়া কলকাতা হয় না।', 'Aḍḍa chhaṛa Kolkata hoy na.', 'Sem uma boa conversa (adda) não existe Calcutá.'],
    ],
  },
};
